name: release

on: push

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # https://github.com/actions/checkout v4.2.2

      - name: Build Artifacts
        run: cmd.exe /c '.\scripts\make-artifacts.bat'

      - name: Archive Artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # https://github.com/actions/upload-artifact v4.4.3
        with:
           name: "artifacts"
           path: artifacts

      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # https://github.com/softprops/action-gh-release v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
